[env]
TERM = "xterm-256color"

[window]
padding.x = 1
padding.y = 1
dynamic_padding = true

decorations = "Buttonless"

opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font Mono"
size = 18
offset.x = 3  # letter spacing
offset.y = 16 # line spacing

# generate tokyo night color scheme for alacritty
[colors.primary]
background = "#222334"
foreground = "#cad2f2"

[colors.normal]
black = "#1b1c29"
red = "#ed7d81"
green = "#cae697"
yellow = "#f6c982"
blue = "#8aa8f8"
magenta = "#bb9af8"
cyan = "#9bdef8"
white = "#838ab4"

[colors.bright]
black = "#454970"
red = "#ed7d81"
green = "#cae697"
yellow = "#f6c982"
blue = "#8aa8f8"
magenta = "#bb9af8"
cyan = "#9bdef8"
white = "#838ab4"

