[tools]
opam = "latest"
ruby = "latest"
gleam = "latest"
python = "latest"
awscli = "latest"
java = "latest"
dotnet = "latest"
erlang = "latest"
node = "latest"
bun = "latest"
deno = "latest"
go = "1.25.6"
zig = "latest"
pnpm = "latest"
yarn = "latest"
biome = "latest"
odin = { version = "latest", exe = "odin" }
"go:github.com/air-verse/air" = "latest"
"go:github.com/golang-migrate/migrate/v4/cmd/migrate" = { version = "latest", tags = "postgres mysql sqlite3" }
"go:github.com/pressly/goose/v3/cmd/goose" = "latest"
"go:github.com/fzipp/gocyclo/cmd/gocyclo" = "latest"
"go:github.com/golangci/golangci-lint/v2/cmd/golangci-lint" = "2.8.0"
"go:github.com/fatih/gomodifytags" = "latest"
"go:github.com/securego/gosec/v2/cmd/gosec" = "latest"
"go:go.uber.org/mock/mockgen" = "latest"
"go:github.com/sqlc-dev/sqlc/cmd/sqlc" = "latest"
"go:github.com/a-h/templ/cmd/templ" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
atuin = "latest"
atlas-community = "1.1.1"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]

[settings.ruby]
compile = false

