#!/usr/bin/env bash

# Check for GNU Stow
if ! command -v stow &> /dev/null
then
    echo "GNU Stow could not be found, please install it first."
    exit
fi

mkdir -p $HOME/.config

### Stow finished
# ZSH
echo COPYING .zshrc
rm -rf $HOME/.zshrc
rm -rf $HOME/.config/zsh
stow --target=$HOME zsh
if [ ! -d "$HOME/.oh-my-zsh" ]; then
    echo INSTALLING ZSHRC
    KEEP_ZSHRC=yes sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

# TMux
echo COPYING tmux.conf
rm -rf $HOME/.config/tmux
stow --target=$HOME tmux

# Neovim
echo COPYING .config/nvim
rm -rf $HOME/.config/nvim
stow --target=$HOME nvim

# Starship
echo COPYING .config/starship.toml
rm -rf $HOME/.config/starship.toml
stow --target=$HOME starship

# echo COPYING .gitconfig
rm -rf $HOME/.gitconfig
rm -rf $HOME/.config/git
stow --target=$HOME git
git config --global core.excludesFile $HOME/.config/git/.gitignore_global
# configuring diff-so-fancy to be used by git
git config --global core.pager "diff-so-fancy | less --tabs=4 -RF"
git config --global interactive.diffFilter "diff-so-fancy --patch"

# Ghostty Terminal Emulator
echo COPYING .config/ghostty/config
rm -rf $HOME/.config/ghostty
stow --target=$HOME ghostty

# Wezterm Terminal Emulator
echo COPYING .wezterm.lua
rm -rf $HOME/.wezterm.lua
stow --target=$HOME wezterm

# Alactritty Terminal Emulator
echo COPYING .config/alacritty/alacritty.toml
rm -rf $HOME/.config/alacritty/
stow --target=$HOME alacritty

# Mise
echo COPYING .config/mise
rm -rf $HOME/.config/mise
stow --target=$HOME mise

# Newsboat RSS Reader
echo COPYING .newsboat/urls .newsboat/config .newsboat/dark
rm -rf $HOME/.newsboat
stow --target=$HOME newsboat

# Zed Editor Settings
echo COPYING .config/zed/
rm -rf $HOME/.config/zed
stow --target=$HOME zed

# NPM configuration for global packages
echo COPYING .npmrc
rm -rf $HOME/.npmrc
stow --target=$HOME npm

# Ideavim config
echo COPYING .ideavimrc
rm -rf $HOME/.ideavimrc
stow --target=$HOME jetbrains

### To Stow

echo COPYING scripts
mkdir -p $HOME/.local/bin
rm -rf $HOME/.local/bin/t
# ln -s $DOTFILES/scripts/t $HOME/.local/bin/t

# installing fzf-tab
mkdir -p $HOME/.config/
git clone https://github.com/Aloxaf/fzf-tab $HOME/.config/

source ~/.zshrc
