#!/usr/bin/env bash

# node.js
asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
asdf install nodejs latest
asdf global nodejs latest
# to add global packages:
# npm i -g yarn
# asdf reshim nodejs

# deno
asdf plugin-add deno https://github.com/asdf-community/asdf-deno.git
asdf install deno latest
asdf global deno latest

# bun
asdf plugin add bun
asdf install bun latest
asdf global bun latest

# GO
asdf plugin-add golang https://github.com/kennyp/asdf-golang.git
asdf install golang latest
asdf global golang latest

# PHP
# asdf plugin-add php https://github.com/asdf-community/asdf-php.git
# asdf install php latest
# asdf global php latest
# Adding extensions:
# pecl install redis
# pecl install imagick
# echo "extension=redis.so
# extension=imagick.so" > $(asdf where php)/conf.d/php.ini
# Global packages
# composer global require friendsofphp/php-cs-fixer
# asdf reshim
#
# Dart
asdf plugin-add dart https://github.com/patoconnor43/asdf-dart.git
asdf list all dart 2
asdf install dart 2.19.6
asdf list all dart 3
asdf install dart 3.0.0
asdf install dart latest
asdf global dart latest

# Flutter
# asdf plugin-add flutter
# asdf list all flutter 2
# asdf install flutter 2.10.5-stable
# asdf install flutter 2.10.5
# asdf plugin-remove flutter
#
# Rust
asdf plugin-add rust https://github.com/code-lever/asdf-rust.git
asdf install rust latest
asdf global rust latest

# Zig
asdf plugin-add zig https://github.com/cheetah/asdf-zig.git
asdf install zig latest
asdf install zig master
asdf global zig master # experimental dev build ...
