# OH MY ZSH
# export ZSH="$HOME/.oh-my-zsh"
# ZSH_THEME="amuse"
#
# plugins=(
# 	git
# 	# asdf
# 	fzf-tab
# 	zsh-autosuggestions # git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
# )
#
# source $ZSH/oh-my-zsh.sh
#
# STARTSHIP
eval "$(starship init zsh)"

export LANG=en_US.UTF-8

[ -f "$HOME/git/dotfiles/zsh/aliases.zsh" ] && source "$HOME/git/dotfiles/zsh/aliases.zsh"
[ -f "$HOME/git/dotfiles/zsh/services.zsh" ] && source "$HOME/git/dotfiles/zsh/services.zsh"
[ -f "$HOME/git/dotfiles/zsh/languages.zsh" ] && source "$HOME/git/dotfiles/zsh/languages.zsh"

# MISE version manager - Mise is a tool to manage your shell environment.
# eval "$(/Users/dannyfestor/.local/bin/mise activate zsh)"
eval "$(/opt/homebrew/bin/mise activate zsh)"


# bun completions
[ -s "/Users/dannyfestor/.bun/_bun" ] && source "/Users/dannyfestor/.bun/_bun"


# Herd injected PHP binary.
# export PATH="/Users/dannyfestor/Library/Application Support/Herd/bin/":$PATH


# Herd injected PHP 8.3 configuration.
# export HERD_PHP_83_INI_SCAN_DIR="/Users/dannyfestor/Library/Application Support/Herd/config/php/83/"


# Herd injected PHP 8.4 configuration.
# export HERD_PHP_84_INI_SCAN_DIR="/Users/dannyfestor/Library/Application Support/Herd/config/php/84/"


# Herd injected PHP 8.2 configuration.
# export HERD_PHP_82_INI_SCAN_DIR="/Users/dannyfestor/Library/Application Support/Herd/config/php/82/"


# Herd injected PHP 8.1 configuration.
# export HERD_PHP_81_INI_SCAN_DIR="/Users/dannyfestor/Library/Application Support/Herd/config/php/81/"


# Herd injected PHP 8.0 configuration.
# export HERD_PHP_80_INI_SCAN_DIR="/Users/dannyfestor/Library/Application Support/Herd/config/php/80/"


# Herd injected PHP 7.4 configuration.
# export HERD_PHP_74_INI_SCAN_DIR="/Users/dannyfestor/Library/Application Support/Herd/config/php/74/"
