# OH MY ZSH
# export ZSH="$HOME/.oh-my-zsh"
# ZSH_THEME="amuse"
#
# plugins=(
# 	git
# 	# asdf
# 	fzf-tab
# 	zsh-autosuggestions # git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
# )
#
# source $ZSH/oh-my-zsh.sh
#
# STARTSHIP
eval "$(starship init zsh)"

export LANG=en_US.UTF-8

[ -f "$HOME/git/dotfiles/zsh/aliases.zsh" ] && source "$HOME/git/dotfiles/zsh/aliases.zsh"
[ -f "$HOME/git/dotfiles/zsh/services.zsh" ] && source "$HOME/git/dotfiles/zsh/services.zsh"
[ -f "$HOME/git/dotfiles/zsh/languages.zsh" ] && source "$HOME/git/dotfiles/zsh/languages.zsh"

# MISE version manager - Mise is a tool to manage your shell environment.
# eval "$(/Users/dannyfestor/.local/bin/mise activate zsh)"
eval "$(/opt/homebrew/bin/mise activate zsh)"

